import slicer


UNASSIGNED_POINT = ""
BRANCH_POINT = "Branch point"
EDGE_POINT = "Free Edge point"
INTERIOR_POINT = "Interior point"
OTHER_POINT = "Other"


TAG_TYPES = [UNASSIGNED_POINT, BRANCH_POINT, EDGE_POINT, INTERIOR_POINT, OTHER_POINT]

SCALAR_RADIUS_NAME = "Radius"
SCALAR_POINT_ANATOMICAL_INDEX_NAME = "Label"
SCALAR_TRIANGLE_ANATOMICAL_INDEX_NAME = "TriangleLabel"
SCALAR_TRIANGLE_COLOR_NAME = "Colors"

SCALAR_NAMES = [SCALAR_TRIANGLE_COLOR_NAME, SCALAR_RADIUS_NAME,
                SCALAR_POINT_ANATOMICAL_INDEX_NAME, SCALAR_TRIANGLE_ANATOMICAL_INDEX_NAME]

SCALAR_COLOR_NODE_IDS = {
  SCALAR_RADIUS_NAME: "vtkMRMLColorTableNodeFileDivergingBlueRed.txt",
  SCALAR_TRIANGLE_COLOR_NAME: "vtkMRMLColorTableNodeLabels",
  SCALAR_POINT_ANATOMICAL_INDEX_NAME: "vtkMRMLColorTableNodeLabels"
}


PARAM_POINT_GLYPH_SIZE = "GlyphSizePerCent"
PARAM_INPUT_MODEL = "InputModel"
PARAM_OUTPUT_MODEL = "OutputModel"
PARAM_SUBDIVISION_PREVIEW_MODEL = "SubdivisionModel"
PARAM_INFLATED_MODEL = "InflatedModel"
PARAM_CURRENT_POINT_LABEL_LIST = "CurrentPointLabelList"
PARAM_CURRENT_TRIANGLE_LABEL_LIST = "CurrentTriangleLabelList"
PARAM_GRID_TYPE = "GridType"
PARAM_GRID_MODEL_SOLVER_TYPE = "GridModelSolverType"
PARAM_GRID_MODEL_ATOM_SUBDIVISION_LEVEL = "GridModelSubdivisionLevel"
PARAM_GRID_MODEL_COEFFICIENT_CONSTANT_RHO = "GridModelCoefficientConstantRho"
PARAM_GRID_MODEL_COEFFICIENT_USE_CONSTANT_RADIUS = "GridModelCoefficientUseConstantRadius"
PARAM_GRID_MODEL_COEFFICIENT_CONSTANT_RADIUS = "GridModelCoefficientConstantRadius"
PARAM_GRID_MODEL_INFLATE = "GridModelInflate"
PARAM_GRID_MODEL_INFLATE_RADIUS = "GridModelInflateRadius"
PARAM_OUTPUT_DIRECTORY = "OutputDirectory"
PARAM_AUTO_SAVE = "AutoSave"
PARAM_OUTPUT_MODEL_SCALAR_NAME = "OutputModelScalar"


PARAM_DEFAULTS = {
  PARAM_POINT_GLYPH_SIZE: 3,
  PARAM_INPUT_MODEL: "",
  PARAM_OUTPUT_MODEL: "",
  PARAM_SUBDIVISION_PREVIEW_MODEL: "",
  PARAM_INFLATED_MODEL: "",
  PARAM_CURRENT_POINT_LABEL_LIST: "",
  PARAM_CURRENT_TRIANGLE_LABEL_LIST: "",
  PARAM_GRID_TYPE: "LoopSubdivision",
  PARAM_GRID_MODEL_SOLVER_TYPE: "BruteForce",
  PARAM_GRID_MODEL_ATOM_SUBDIVISION_LEVEL: 0,
  PARAM_GRID_MODEL_COEFFICIENT_CONSTANT_RHO: -0.001,
  PARAM_GRID_MODEL_COEFFICIENT_CONSTANT_RADIUS: 0.5,
  PARAM_GRID_MODEL_COEFFICIENT_USE_CONSTANT_RADIUS: False,
  PARAM_GRID_MODEL_INFLATE: False,
  PARAM_GRID_MODEL_INFLATE_RADIUS: 1.0,
  PARAM_OUTPUT_DIRECTORY: slicer.app.temporaryPath,
  PARAM_AUTO_SAVE: False,
  PARAM_OUTPUT_MODEL_SCALAR_NAME: SCALAR_TRIANGLE_COLOR_NAME
}


DEFAULT_TRIANGLE_COLOR = "#ff0000"
DEFAULT_POINT_COLOR = [1,1,1]