
UNASSIGNED_POINT = ""
BRANCH_POINT = "Branch point"
EDGE_POINT = "Free Edge point"
INTERIOR_POINT = "Interior point"
OTHER_POINT = "Other"

TAG_TYPES = [UNASSIGNED_POINT, BRANCH_POINT, EDGE_POINT, INTERIOR_POINT, OTHER_POINT]